import type { ReactNode } from "react";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { cx } from "class-variance-authority";
import { SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cookieStore = await cookies();
  const usrTheme = cookieStore.get("theme");
  let theme = null;
  if (usrTheme?.value === "light" || usrTheme?.value === "dark") {
    theme = usrTheme.value;
  }
  return (
    <html lang="en">
      <body
        className={cx(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          theme,
        )}
      >
        <SidebarProvider>
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
